services:
  course-explorer-monorepo-database:
    platform: linux/amd64
    image: mysql
    container_name: course-explorer-monorepo-database
    ports:
      - 6000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=course-explorer-monorepo
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    networks:
      - course-explorer-monorepo-networks
    volumes:
      - course-explorer-monorepo-volumes:/var/lib/mysql
      - ./course-explorer-monorepo.sql:/docker-entrypoint-initdb.d/course-explorer-monorepo.sql
  course-explorer-monorepo-api-content:
    platform: linux/amd64
    image: gatherloop/course-explorer-monorepo-api-content
    container_name: course-explorer-monorepo-api-content
    environment:
      - DB_HOST=course-explorer-monorepo-database
      - DB_PORT=6000
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=course-explorer-monorepo
      - PORT=3000
    ports:
      - 6100:3000
    depends_on:
      course-explorer-monorepo-database:
        condition: service_healthy
    networks:
      - course-explorer-monorepo-networks
  course-explorer-monorepo-api-gateway:
    platform: linux/amd64
    image: gatherloop/course-explorer-monorepo-api-gateway
    container_name: course-explorer-monorepo-api-gateway
    environment:
      - PORT=3000
      - CONTENT_API_URL=https://course-explorer-api-content.gatherloop.co
    ports:
      - 6101:3000
    depends_on:
      course-explorer-monorepo-database:
        condition: service_healthy
    networks:
      - course-explorer-monorepo-networks
  course-explorer-monorepo-api-user:
    platform: linux/amd64
    image: gatherloop/course-explorer-monorepo-api-user
    container_name: course-explorer-monorepo-api-user
    environment:
      - DB_HOST=course-explorer-monorepo-database
      - DB_PORT=6000
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=course-explorer-monorepo
      - PORT=3000
    ports:
      - 6102:3000
    depends_on:
      course-explorer-monorepo-database:
        condition: service_healthy
    networks:
      - course-explorer-monorepo-networks
  course-explorer-monorepo-ui-cms:
    platform: linux/amd64
    image: gatherloop/course-explorer-monorepo-ui-cms
    container_name: course-explorer-monorepo-ui-cms
    environment:
      - API_URL=https://gw-course-explorer.gatherloop.co
    ports:
      - 6200:3000
    networks:
      - course-explorer-monorepo-networks
  course-explorer-monorepo-ui-explorer:
    platform: linux/amd64
    image: gatherloop/course-explorer-monorepo-ui-explorer
    container_name: course-explorer-monorepo-ui-explorer
    environment:
      - API_URL=https://gw-course-explorer.gatherloop.co
    ports:
      - 6201:3000
    networks:
      - course-explorer-monorepo-networks
networks:
  course-explorer-monorepo-networks:
    name: course-explorer-monorepo-networks
volumes:
  course-explorer-monorepo-volumes:
    name: course-explorer-monorepo-volumes
